title: Mattia Astorino
subtitle: null
description: >-
  I'm a 29-year-old guy born in Italy. I'm a UXD Lead Engineer and CSS/HTML
  architect in Milan.
keywords: null
author: Mattia Astorino
language: null
timezone: null
all_minifier: true
image_minifier:
  enable: true
autoprefixer:
  exclude:
    - '*.min.css'
  browsers:
    - last 1 versions
url: 'https://equinsuocha.io'
root: /
permalink: 'blog/:title/'
permalink_defaults: null
source_dir: source
public_dir: build
tag_dir: tags
archive_dir: blog
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: 'MMMM Do, YYYY'
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: cactus
theme_config:
  colorscheme: white
  rss: null
  open_graph:
    twitter_id: equinusocio
  logo:
    enabled: true
    width: 50
    height: 50
    url: /images/logo.png
    gravatar: false
  social_links:
    github: 'https://github.com/equinusocio'
    twitter: 'https://twitter.com/equinusocio'
    dribbble: 'https://dribbble.com/astorino_mattia'
    stack-overflow: 'https://stackoverflow.com/story/mattia.astorino'
    codepen: 'https://codepen.io/equinusocio'
  nav:
    Home: /
    About: /about/
    Blog: /blog/
  google_analytics:
    enabled: true
    id: UA-117081439-1
  favicon:
    desktop:
      url: /images/favicon.png
      gravatar: false
    android:
      url: /images/favicon-192x192.png
      gravatar: false
    apple:
      url: /images/apple-touch-icon.png
      gravatar: false
deploy:
  type: git
  repo: 'git@github.com:equinusocio/equinusocio.github.io.git'
  branch: master
